# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  none

variables:
  GROUP: 'AzureMLRG'
  WORKSPACE: 'AzureMLWS'
  LOCATION: "eastus"

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  name: InstalAzML
  inputs:
    azureSubscription: 'BW-SandBox'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      az upgrade --yes
      az extension add -n ml
      az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION

- task: AzureCLI@2
  name: CreateCompute
  inputs:
    azureSubscription: 'BW-SandBox'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      az ml compute create --file project/compute.yml

- task: AzureCLI@2
  name: CreateEnvironment
  inputs:
    azureSubscription: 'BW-SandBox'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      az ml environment create --file project/environment.yml

- task: AzureCLI@2
  name: TrainModel
  inputs:
    azureSubscription: 'BW-SandBox'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      az ml job create --file project/pipeline.yml
