# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  condition: 
- task: AzureCLI@2
  name: InstalAzML
  inputs:
    azureSubscription: 'BW-SandBox'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      az upgrade
      az extension add -n ml

- task: AzureCLI@2
  name: CreateCompute
  inputs:
    azureSubscription: 'BW-SandBox'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      az ml compute create --file project/compute.yml

- task: AzureCLI@2
  name: CreateEnvironment
  inputs:
    azureSubscription: 'BW-SandBox'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      az ml environment create --file project/environment.yml

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
