$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: pytorch-deployment
endpoint_name: pytorch-model-deployment
model: azureml:pytorch-test@latest
code_configuration:
  code: "./src/score/"
  scoring_script: score_with_data.py
environment: azureml:scoreenvironment@latest
environment_variables:
    SUBSCRIPTION_ID: "3e2547d0-1f1a-4310-bf82-d94871df16ad"
    RESOURCE_GROUP: "AzureMLRG"
    WORKSPACE_NAME: "AzureMLWS"
instance_type: Standard_NC4as_T4_v3
instance_count: 1